--- 

- name: Prepare host with ubuntu system
  hosts: ubuntu

  tasks:

     - name: install python3 and python2
       raw: sudo apt-get update; sudo apt-get install python2.7 python-pip python3 python3-pip curl -y

- name: Prepare host with centos
  hosts: centos

  tasks:
  
      - name: Install python3 and python2
        raw: sudo yum install python python-pip python3 python3-pip curl -y


  