---
- name: Show hosts IP
  hosts: allhosts
  become: yes
  gather_facts: yes
  vars: 
    serwer_www_centos: httpd

  tasks:
   - name: Show IP
     debug:
       msg: "Your host is {{ ansible_host }}  IP {{ ansible_all_ipv4_addresses }}" 
# Install apache httpd (www server on centos)
   - name: Install apache httpd (www server on centos)
     yum:
      name: "{{ serwer_www_centos }}"
