---

- hosts: ubuntu
  gather_facts: no
  become: yes
  vars: 
    code_name: martini
    version: 4.5

  tasks:
  - name: deploy configuration file
    template:
     src: ./config.j2
     dest: /opt/config